# Generated by Django 3.0.3 on 2020-03-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(verbose_name='in_id')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ Заказа')),
                ('design_plan_start_date', models.DateField(blank=True, null=True, verbose_name='Начало по плану')),
                ('design_plan_end_date', models.DateField(blank=True, null=True, verbose_name='Окончание по плану')),
                ('design_fact_end_date', models.DateField(blank=True, null=True, verbose_name='Окончание по факту')),
                ('design_need', models.BooleanField(blank=True, default=False, null=True, verbose_name='Нужен ли документ')),
                ('design_dispatcher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диспетчер')),
            ],
            options={
                'verbose_name': 'Конструкторскую Документацию (КД)',
                'verbose_name_plural': 'Конструкторская документация (КД), даты',
            },
        ),
        migrations.CreateModel(
            name='PickupDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(verbose_name='ИД')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ Заказа')),
                ('pickup_plan_start_date', models.DateField(blank=True, null=True, verbose_name='Начало по плану')),
                ('pickup_plan_end_date', models.DateField(blank=True, null=True, verbose_name='Окончание по плану')),
                ('pickup_fact_end_date', models.DateField(blank=True, null=True, verbose_name='Окончание по факту')),
                ('pickup_need', models.BooleanField(blank=True, default=True, null=True, verbose_name='Нужен ли документ')),
                ('pickup_dispatcher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диспетчер')),
            ],
            options={
                'verbose_name': 'Комплектовочную Ведомость (КВ)',
                'verbose_name_plural': 'Комплектовочные Ведомости (КВ), даты',
            },
        ),
        migrations.CreateModel(
            name='ServiceNoteDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(verbose_name='in_id')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ Заказа')),
                ('sn_plan_start_date', models.DateField(blank=True, null=True, verbose_name='Начало по плану')),
                ('sn_plan_end_date', models.DateField(blank=True, null=True, verbose_name='Окончание по плану')),
                ('sn_fact_end_date', models.DateField(blank=True, null=True, verbose_name='Окончание по факту')),
                ('sn_need', models.BooleanField(blank=True, default=True, null=True, verbose_name='Нужен ли документ')),
                ('sn_dispatcher', models.CharField(blank=True, default='Коваленко И.С.', max_length=255, null=True, verbose_name='Диспетчер')),
            ],
            options={
                'verbose_name': 'Служебную записку (СЗ)',
                'verbose_name_plural': 'Служебные записки (СЗ), даты',
            },
        ),
        migrations.CreateModel(
            name='ShipmentDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(verbose_name='ИД')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ Заказа')),
                ('shipment_plan_start_date', models.DateField(blank=True, null=True, verbose_name='Начало по плану')),
                ('shipment_plan_end_date', models.DateField(blank=True, null=True, verbose_name='Окончание по плану')),
                ('shipment_fact_end_date', models.DateField(blank=True, null=True, verbose_name='Окончание по факту')),
                ('shipment_need', models.BooleanField(blank=True, default=True, null=True, verbose_name='Нужен ли документ')),
                ('shipment_dispatcher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диспетчер')),
            ],
            options={
                'verbose_name': 'Отгрузочную Спецификацию (ОС)',
                'verbose_name_plural': 'Отгрузочные Спецификации (ОС), даты',
            },
        ),
    ]
