# Generated by Django 3.0.3 on 2020-03-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(verbose_name='in_id')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ Заказа')),
                ('design_plan_start_date', models.DateField(blank=True, null=True, verbose_name='Начало работ по плану')),
                ('design_plan_end_date', models.DateField(blank=True, null=True, verbose_name='Конец работ по плану')),
                ('design_fact_end_date', models.DateField(blank=True, null=True, verbose_name='Конец работ по факту')),
                ('design_need', models.BooleanField(blank=True, default=True, null=True, verbose_name='Нужен ли документ')),
                ('design_dispatcher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диспетчер')),
            ],
            options={
                'verbose_name': 'КД дата',
                'verbose_name_plural': 'КД даты',
            },
        ),
        migrations.CreateModel(
            name='PickupDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(verbose_name='in_id')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ Заказа')),
                ('pickup_plan_start_date', models.DateField(blank=True, null=True, verbose_name='Начало работ по плану')),
                ('pickup_plan_end_date', models.DateField(blank=True, null=True, verbose_name='Конец работ по плану')),
                ('pickup_fact_end_date', models.DateField(blank=True, null=True, verbose_name='Конец работ по факту')),
                ('pickup_need', models.BooleanField(blank=True, default=True, null=True, verbose_name='Нужен ли документ')),
                ('pickup_dispatcher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диспетчер')),
            ],
            options={
                'verbose_name': 'КВ дата',
                'verbose_name_plural': 'КВ даты',
            },
        ),
        migrations.CreateModel(
            name='ServiceNoteDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(verbose_name='in_id')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ Заказа')),
                ('sn_plan_start_date', models.DateField(blank=True, null=True, verbose_name='Начало работ по плану')),
                ('sn_plan_end_date', models.DateField(blank=True, null=True, verbose_name='Конец работ по плану')),
                ('sn_fact_end_date', models.DateField(blank=True, null=True, verbose_name='Конец работ по факту')),
                ('sn_need', models.BooleanField(blank=True, default=True, null=True, verbose_name='Нужен ли документ')),
                ('sn_dispatcher', models.CharField(blank=True, default='Коваленко И.С.', max_length=255, null=True, verbose_name='Диспетчер')),
            ],
            options={
                'verbose_name': 'СЗ дата',
                'verbose_name_plural': 'СЗ даты',
            },
        ),
        migrations.CreateModel(
            name='ShipmentDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(verbose_name='in_id')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ Заказа')),
                ('shipment_plan_start_date', models.DateField(blank=True, null=True, verbose_name='Начало работ по плану')),
                ('shipment_plan_end_date', models.DateField(blank=True, null=True, verbose_name='Конец работ по плану')),
                ('shipment_fact_end_date', models.DateField(blank=True, null=True, verbose_name='Конец работ по факту')),
                ('shipment_need', models.BooleanField(blank=True, default=True, null=True, verbose_name='Нужен ли документ')),
                ('shipment_dispatcher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диспетчер')),
            ],
            options={
                'verbose_name': 'ОС дата',
                'verbose_name_plural': 'ОС даты',
            },
        ),
    ]
