# Generated by Django 3.0.3 on 2020-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedocumentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdates',
            name='design_need',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Нужен ли документ'),
        ),
    ]
