# Generated by Django 3.0.3 on 2020-03-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWorkplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(verbose_name='in_id')),
                ('start_date', models.DateField(verbose_name='Начало работ')),
                ('end_date', models.DateField(verbose_name='Конец работ')),
                ('letter', models.CharField(max_length=2, verbose_name='Буква')),
                ('shop', models.CharField(max_length=2, verbose_name='Буква цеха')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
