# Generated by Django 3.0.3 on 2020-03-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(unique=True, verbose_name='ID')),
                ('shipment_from', models.DateField(blank=True, null=True, verbose_name='Отгрузка "от"')),
                ('shipment_before', models.DateField(blank=True, null=True, verbose_name='Отгрузка "до"')),
                ('personal_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='П/н')),
                ('according_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Согласно КП №')),
                ('pruduct_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип продукции')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Продукция')),
                ('couterparty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контрагент')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ Заказа')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Кол-во')),
                ('sn_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ СЗ')),
                ('sn_no_amended', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ СЗ с изменениями')),
                ('sn_plan_days', models.SmallIntegerField(blank=True, null=True, verbose_name='Комплектовочные План Дней')),
                ('sn_plan_work_days', models.SmallIntegerField(blank=True, null=True, verbose_name='Комплектовочные План Рабочих Дней')),
                ('sn_plan_date', models.DateField(blank=True, null=True, verbose_name='Комплектовочные План Дата')),
                ('pickup_plan_days', models.SmallIntegerField(blank=True, null=True, verbose_name='Комплектовочные План Дней')),
                ('pickup_plan_work_days', models.SmallIntegerField(blank=True, null=True, verbose_name='Комплектовочные План Рабочих Дней')),
                ('pickup_plan_date', models.DateField(blank=True, null=True, verbose_name='Комплектовочные План Дата')),
                ('shipping_plan_days', models.SmallIntegerField(blank=True, null=True, verbose_name='Отгрузочные План Дней')),
                ('shipping_plan_work_days', models.SmallIntegerField(blank=True, null=True, verbose_name='Отгрузочные План Рабочих Дней')),
                ('shipping_plan_date', models.DateField(blank=True, null=True, verbose_name='Отгрузочные План Дата')),
                ('design_plan_days', models.SmallIntegerField(blank=True, null=True, verbose_name='Конструкторская документация План Дней')),
                ('design_plan_work_days', models.SmallIntegerField(blank=True, null=True, verbose_name='Конструкторская документация План Рабочих Дней')),
                ('design_plan_date', models.DateField(blank=True, null=True, verbose_name='Конструкторская документация План Дата')),
                ('material_plan_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Материалы План Дней')),
                ('material_plan_work_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Материалы План Рабочих Дней')),
                ('material_plan_date', models.DateField(blank=True, null=True, verbose_name='Материалы План Дата')),
                ('ready_status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Готов')),
                ('produced', models.BooleanField(blank=True, default=True, null=True, verbose_name='Производится')),
                ('ready_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('failure_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отсутствие тех документации')),
                ('failure_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дефицит материалов')),
                ('failure_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дефицит мощностей')),
                ('failure_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Нет технологической возможности (аутсорс)')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
